eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://service-registry:8762/eureka}

okta:
  oauth2:
    issuer: https://trial-3029621.okta.com/oauth2/default
    audience: api://default